project:
  type: website
  output-dir: docs

website:
  title: "Emils Steine Block"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer:
    left: "üß± Blog mit ‚ù§Ô∏è gebaut von Emil und Jan"

lang: de

format:
  html:
    theme: yeti
    css: styles.css

editor: visual
